### ISSUE TITLE
basic authentication scheme selected

### ISSUE THREAD

**Issue by ving0099** [dwins/mapnik2geotools#43]
what is the error ?

[error] Feb 02, 2015 3:09:29 AM org.apache.commons.httpclient.auth.AuthChallengeProcessor selectAuthScheme
[error] INFO: basic authentication scheme selected

**Comment by dwins** [comment]
It has been a while since I have used this tool, but I believe that it is simply an informational message and not necessarily an error that needs to be addressed.  SBT prints '[error]` because this message is printed to standard error (http://en.wikipedia.org/wiki/Standard_streams#Standard_error_.28stderr.29 .)

Unless you are finding that the software is not producing the expected results I think you can ignore this message safely.  If you do find some problems let me know in a new bug report and maybe I can give better advice.
